puphpet.vagrantfile_linode.homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:VagrantfileLinode:index }

puphpet.vagrantfile_linode.multi_machine:
    pattern: /multi-machine
    defaults: { _controller: PuphpetMainBundle:VagrantfileLinode:multiMachine }

puphpet.vagrantfile_linode.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetMainBundle:VagrantfileLinode:syncedFolder }
