puphpet.vagrantfile_softlayer.homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:VagrantfileSoftlayer:index }

puphpet.vagrantfile_softlayer.multi_machine:
    pattern: /multi-machine
    defaults: { _controller: PuphpetMainBundle:VagrantfileSoftlayer:multiMachine }

puphpet.vagrantfile_softlayer.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetMainBundle:VagrantfileSoftlayer:syncedFolder }
