target: ~

vm:
    multi_machine_enabled: 0
    multi_machine:
        -
            id: machine1
            hostname: machine1.puphpet
            server_name: machine1-puphpet
            region: dfw

    provider:
        rackspace:
            server_name: rackspace-server
            image: 598a4282-f14b-4e50-af4c-b3e52749d9f9
            region: dfw
            size: 1GB
            username: RACKSPACE_USERNAME
            api_key: RACKSPACE_API_KEY
    synced_folder:
        -
            source: ./
            target: /var/www
            id: webroot
            nfs: false
    provision:
        puppet:
            manifests_path: "puphpet/puppet/manifests"
            module_path: "puphpet/puppet/modules"
            options:
                - "--verbose"
                - "--hiera_config /vagrant/puphpet/puppet/hiera.yaml"
ssh:
    username: PRIVATE_KEY_USER
    forward_agent: true
    private_key_path: "~/.ssh/id_rsa"
    public_key_path: "~/.ssh/id_rsa.pub"
