target: ~

vm:
    box: puphpet/ubuntu1404-x64
    box_url: puphpet/ubuntu1404-x64
    hostname: puphpet-box
    memory: 512
    cpus: 1
    chosen_provider: virtualbox
    box_version: ~
    multi_machine_enabled: ~
    multi_machine: []
    network:
        private_network: 192.168.56.101
        forwarded_port: []
    post_up_message: ''
    provider:
        virtualbox:
            modifyvm:
                natdnshostresolver1: false
            showgui: ~
        vmware:
            numvcpus: 1
        parallels:
            use_linked_clone: 0
            check_guest_tools: 0
            update_guest_tools: 0
    provision:
        puppet:
            manifests_path: 'puphpet/puppet/manifests'
            module_path: 'puphpet/puppet/modules'
            options:
                - '--verbose'
                - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
    synced_folder: []
    usable_port_range:
        start: 10200
        stop: 10500

ssh:
    host: ~
    port: ~
    private_key_path: ~
    username: vagrant
    guest_port: ~
    keep_alive: true
    forward_agent: false
    forward_x11: false
    shell: bash -l
    insert_key: false

vagrant:
    host: detect

proxy:
    http: ~
    https: ~
    ftp: ~
    no_proxy: ''
