target: local

vm:
    box: puphpet/ubuntu1404-x64
    box_url: puphpet/ubuntu1404-x64
    hostname: local.puphpet
    chosen_provider: virtualbox
    box_version: ~
    multi_machine_enabled: 0
    multi_machine:
        -
            id: machine1
            private_network: 192.168.56.101
            hostname: machine1.puphpet
            forwarded_port:
                -
                    host: ~
                    guest: ~
    provider:
        virtualbox:
            modifyvm:
                natdnshostresolver1: false
            showgui: 0
        vmware: []
        parallels:
            use_linked_clone: 0
            check_guest_tools: 0
            update_guest_tools: 0
    synced_folder:
        -
            source: ./
            target: /var/www
            id: vagrant-root
            sync_type: default
            owner: 'www-data'
            group: 'www-data'
            smb:
                smb_host: ~
                smb_username: ~
                smb_password: ~
                mount_options:
                    dir_mode: '0775'
                    file_mode: '0664'
            rsync:
                args:
                    - '--verbose'
                    - '--archive'
                    - '-z'
                exclude:
                    - '.vagrant/'
                    - '.git/'
                auto: true
    network:
        forwarded_port:
            -
                guest: ~
                host: ~
    post_up_message: ''
    provision:
        puppet:
            manifests_path: 'puphpet/puppet/manifests'
            module_path: 'puphpet/puppet/modules'
            options:
                - '--verbose'
                - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
    usable_port_range:
        start: 10200
        stop: 10500
ssh:
    forward_agent: true
    insert_key: false
