puphpet.vagrantfile_local.homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:VagrantfileLocal:index }

puphpet.vagrantfile_local.multi_machine:
    pattern: /multi-machine
    defaults: { _controller: PuphpetMainBundle:VagrantfileLocal:multiMachine }

puphpet.vagrantfile_local.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetMainBundle:VagrantfileLocal:syncedFolder }

puphpet.vagrantfile_local.forwarded_port:
    pattern: /forwarded-port
    defaults: { _controller: PuphpetMainBundle:VagrantfileLocal:forwardedPort }


puphpet.vagrantfile_local.multi_machine_forwarded_port:
    pattern: /multi-machine-forwarded-port/{mmId}
    defaults: { _controller: PuphpetMainBundle:VagrantfileLocal:multiMachineForwardedPort }
